# Please put the information of the robot and all the obstacles in this file

loaded_robot:
  name: ur5_info.yaml # please enter the name of the corresponding info file
  link_radius: 0.05 # by default
  objective_mode: ECA # please select from noECA, ECA, ECA3, and ECAA
  input_device: keyboard # please select from keyboard and cartesian_path

obstacles:
  cuboids:
    - name: box1
      scale: [0.35,0.6,0.002]
      translation: [0.6,0.0,0.0]
      rotation: [0.0,0.0,0.0]
      animation: static
  spheres:
    - name: sphere1
      scale: 0.1
      translation: [0.4,0.4,0.3]
      animation: rotations_sphere1
    - name: sphere2
      scale: 0.15
      translation: [0.5,-0.7,0.3]
      animation: rotations_sphere2
    - name: sphere3
      scale: 0.12
      translation: [0.85,0.15,0.3]
      animation: rotations_sphere3
    - name: sphere4
      scale: 0.06
      translation: [0.6,-0.1,0.9]
      animation: static
  point_cloud:
    - name: bunny
      scale: [2.0,2.0,2.0]
      translation: [1.0,-0.25,0.15]
      rotation: [1.57,0.0,-1.57]
      animation: icratrace
      file: bunny